import { ContactForm, ExperienceCard, FAQ, Header, ProgramSchedule } from './components/sections';

export default function Home() {
  const day1=[['07:00','استقبال الضيوف + شاي أعشاب ترحيبي'],['08:00','مشي صامت على الشاطئ Mindful Walking'],['09:00','إفطار صحي بإطلالة البحر'],['10:30','ورشة تعارف عميق بين المجموعة'],['12:30','سباحة حرة + استرخاء'],['14:00','غداء بحري صحي محلي'],['15:30','جلسة كتابة علاجية Journaling على الشاطئ'],['17:00','مشاهدة الغروب جماعياً بصمت'],['19:00','عشاء خفيف + موسيقى أندلسية'],['21:00','جلسة نجوم + أسئلة وجودية جماعية'],['22:30','نوم وراحة']].map(([time,activity])=>({time,activity}));
  const day2=[['06:30','يقظة مع شروق الشمس'],['07:30','تنفس واعٍ Breathwork على الشاطئ'],['09:00','إفطار + تبادل تجارب الليلة'],['10:30','جلسة تدليك بالزيوت الطبيعية'],['12:00','ورشة رسم أو أعمال يدوية'],['14:00','غداء وداع جماعي'],['15:00','مغادرة بروح مختلفة']].map(([time,activity])=>({time,activity}));
  return <main id="home" className="grain relative overflow-hidden">
    <Header />
    <section className="max-w-6xl mx-auto px-4 py-20 grid lg:grid-cols-2 gap-8 items-center reveal"><div><h1 className="text-5xl leading-tight font-bold text-sea mb-4">اهرب من الضجيج… وعد إلى نفسك</h1><p className="mb-6">Soul Escape تجربة استشفاء وسياحة علاجية في الشرق الجزائري، مصممة لتمنحك هدوء البحر، طاقة الطبيعة، غذاءً صحياً، وجلسات تعيد التوازن للجسد والذهن والروح.</p><p className="text-xl text-eucalyptus mb-6">رحلة هادئة نحو جسد أخف، ذهن أصفى، وروح أكثر اتزاناً.</p><div className="flex gap-3"><a href="#booking" className="bg-sea text-white px-6 py-3 rounded-full">ابدأ رحلتك</a><a href="#program" className="border border-sea text-sea px-6 py-3 rounded-full">شاهد البرنامج</a></div></div><div className="bg-gradient-to-br from-sea/90 via-eucalyptus to-sand rounded-[2rem] p-8 text-white shadow-soft"><div className="grid grid-cols-2 gap-3">{['يوغا','تأمل','غذاء صحي','حمامات معدنية','أنشطة طبيعة'].map(i=><div key={i} className="bg-white/20 rounded-2xl p-3">{i}</div>)}</div></div></section>
    <section className="max-w-6xl mx-auto px-4 grid md:grid-cols-4 gap-4">{['مرافقة شخصية','برامج هادئة ومصممة بعناية','طبيعة الشرق الجزائري','غذاء صحي وتجارب جماعية'].map(t=><div key={t} className="bg-white/80 rounded-2xl p-4 shadow-soft">{t}</div>)}</section>
    <section className="max-w-6xl mx-auto px-4 py-20 reveal"><h2 className="text-3xl text-sea mb-4">ما هي Soul Escape؟</h2><p> Soul Escape ليست مجرد رحلة سياحية، بل مساحة هادئة للعودة إلى الذات. ننسّق تجارب استشفاء تجمع بين الطبيعة، الراحة، الحركة الواعية، الورشات الذهنية، الغذاء الصحي، والجلسات الجماعية في أماكن مختارة بعناية في الشرق الجزائري.</p><p className="mt-4 text-sm text-eucalyptus">لا نقدم وعوداً علاجية أو تشخيصاً طبياً، بل نوفّر تجربة استشفائية داعمة ومرافقة منظمة بالتعاون مع شركاء ومواقع مناسبة.</p></section>
    <section id="experiences" className="max-w-6xl mx-auto px-4 py-10"><h2 className="text-3xl text-sea mb-8">تجارب مصممة للراحة والاتزان</h2><div className="grid lg:grid-cols-3 gap-5"><ExperienceCard title="تجربة البحر والهدوء" description="برنامج يمتد ليومين قرب البحر..." items={['مشي صامت على الشاطئ','Journaling علاجي','غروب وتأمل جماعي','موسيقى هادئة وأجواء ليلية']} cta="اكتشف التجربة"/><ExperienceCard title="تجربة الحمامات المعدنية" description="يوم استشفائي يجمع بين الحمام المعدني..." items={['حمام معدني','تدليك بالطمي الطبيعي','Sound Healing','توعية بالتغذية والرياضة']} cta="اكتشف التجربة"/><ExperienceCard title="تجربة العودة إلى الذات" description="تجربة مخصصة لمن يريد التوقف قليلاً..." items={['تنفس واعٍ','ورشات ذهنية','أنشطة طبيعية','عشاء جماعي هادئ']} cta="صمّم تجربتك"/></div></section>
    <section className="max-w-6xl mx-auto px-4 py-16" id="program"><h2 className="text-3xl text-sea mb-8">إيقاع اليوم داخل Soul Escape</h2><div className="grid md:grid-cols-4 gap-4">{[['الصباح','استقبال في منتجع مختار، يوغا خفيفة، شاي أعشاب، وإفطار صحي.'],['النهار','ورشات ذهنية، أنشطة في الطبيعة، سباحة أو استرخاء حسب نوع التجربة.'],['المساء','جلسة تأمل، مشاهدة الغروب، عشاء جماعي، وموسيقى هادئة.'],['الليل','وقت حر، جلسة نجوم، أسئلة جماعية عميقة، وهدوء يساعد على النوم.']].map(([t,d])=><div key={t} className="bg-white/80 rounded-2xl p-4 shadow-soft"><h3 className="text-sea font-semibold">{t}</h3><p className="text-sm mt-2">{d}</p></div>)}</div></section>
    <section className="max-w-6xl mx-auto px-4 py-8 grid lg:grid-cols-2 gap-6"><ProgramSchedule title="برنامج تجربة البحر — اليوم الأول" entries={day1}/><ProgramSchedule title="برنامج تجربة البحر — اليوم الثاني" entries={day2}/></section>
    <section className="max-w-6xl mx-auto px-4 py-8 reveal"><ProgramSchedule title="برنامج الحمامات المعدنية — يوم واحد من الاسترخاء العميق" entries={[['09:00','وصول + ترحيب بالماء المعدني'],['09:30','جلسة تعارف + نفَس واعٍ لمدة 15 دقيقة'],['10:00','حمام معدني استشفائي لمدة 45 دقيقة'],['11:00','تدليك بالطمي الطبيعي'],['12:00','استراحة + شاي أعشاب'],['12:30','ورشة “جسدي رسالة” حول العلاقة بين الجسد والعقل'],['14:00','غداء صحي تقليدي'],['15:30','جلسة تأمل صوتي Sound Healing'],['16:00','ورشة تعريفية بأهمية التغذية السليمة والرياضة'],['17:30','جلسة ختامية + تبادل مشاعر'],['18:30','مغادرة بجسد وروح مرتاحين']].map(([time,activity])=>({time,activity}))}/><p className="text-sm text-eucalyptus mt-3">تختلف تفاصيل البرنامج حسب الموقع، الطقس، عدد المشاركين، واحتياجات المجموعة.</p></section>
    <section id="why" className="max-w-6xl mx-auto px-4 py-12"><h2 className="text-3xl text-sea mb-4">لماذا الشرق الجزائري؟</h2><p className="mb-6">الشرق الجزائري يجمع بين البحر، الجبال، الغابات، الينابيع المعدنية، والضيافة المحلية...</p><div className="grid md:grid-cols-4 gap-4">{['شواطئ هادئة','ينابيع وحمامات معدنية','طبيعة متنوعة','ضيافة محلية أصيلة'].map(v=><div key={v} className="bg-white/80 rounded-2xl p-4">{v}</div>)}</div></section>
    <section className="max-w-6xl mx-auto px-4 py-12"><h2 className="text-3xl text-sea mb-6">ماذا يمكن أن تمنحك التجربة؟</h2><div className="grid md:grid-cols-3 gap-4">{['مساحة للتوقف والتنفس','تخفيف التوتر اليومي','تواصل أعمق مع الذات','نوم وراحة أفضل','غذاء صحي وتجربة جماعية','عودة تدريجية للتوازن'].map(b=><div key={b} className="bg-white/80 rounded-2xl p-4">{b}</div>)}</div></section>
    <section className="max-w-6xl mx-auto px-4 py-12"><h2 className="text-3xl text-sea mb-6">تجارب المشاركين</h2><div className="grid md:grid-cols-3 gap-4">{['كانت أول مرة أشعر أنني توقفت فعلاً عن الركض. البحر، الصمت، والجلسات الجماعية جعلتني أرى أشياء كثيرة داخلي بهدوء.','التجربة كانت منظمة، دافئة، ومختلفة. أكثر ما أحببته هو الجمع بين الطبيعة، الغذاء الصحي، والورشات البسيطة.','خرجت من اليوم أخف نفسياً وجسدياً. لم تكن رحلة عادية، بل مساحة للراحة والصدق مع الذات.'].map(t=><blockquote key={t} className="bg-white/85 rounded-2xl p-4 shadow-soft">“{t}”</blockquote>)}</div></section>
    <section id="faq" className="max-w-4xl mx-auto px-4 py-12"><h2 className="text-3xl text-sea mb-6">الأسئلة الشائعة</h2><FAQ /></section>
    <section id="booking" className="max-w-6xl mx-auto px-4 py-12"><h2 className="text-3xl text-sea mb-3">احجز تجربتك مع Soul Escape</h2><p className="mb-6">أخبرنا بما تحتاجه، وسنقترح عليك تجربة مناسبة تساعدك على الراحة، التنفس، والعودة إلى ذاتك.</p><ContactForm /></section>
    <footer className="bg-sea text-white mt-12"><div className="max-w-6xl mx-auto px-4 py-10 grid md:grid-cols-4 gap-6"><div><h3 className="text-xl">Soul Escape</h3><p className="text-sm mt-2">تجارب استشفاء وسياحة علاجية هادئة في الشرق الجزائري.</p></div><div><h4>روابط سريعة</h4><ul className="text-sm mt-2 space-y-1"><li>الرئيسية</li><li>التجارب</li><li>البرنامج</li></ul></div><div><h4>تواصل</h4><p className="text-sm mt-2">+213 XXX XXX XXX</p><p className="text-sm">info@soulescape.dz</p></div><div><h4>تابعنا</h4><p className="text-sm mt-2">Instagram / Facebook</p></div></div><p className="text-center text-xs pb-6">© {new Date().getFullYear()} Soul Escape. جميع الحقوق محفوظة.</p></footer>
  </main>;
}
